services:
  db:
    container_name: postgres
    image: postgres
    env_file: 
      - .env
    volumes:
      - ./data/db:/var/lib/postgresql/data
  be:
    env_file: 
      - .env
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      - db